### ISSUE TITLE
Command Argument Value Type 변경

### ISSUE THREAD

**Issue by changhyun-cra** [mhkim90/ssdproject-1234#14]
```cpp
struct CommandArgs {
	int addr;
	string value;
};
```

기존 command.h에 구현된 CommandArgs에 대해 불합리가 있는 것 같아 말씀드립니다.
FullRead를 실행하게 되면 0~99까지 Read를 진행하여 Value를 저장해야 하는데, 기존 string type으로는 1개 밖에 저장할 수 없어서 해당 부분을 vector type이나 기존 CommandArgs 구조체를 변경해야할 것 같습니다.

이에 대한 의견 부탁드립니다.
@bootplus-hub @mhkim90 @jh-cra

**Comment by bootplus-hub** [comment]
좋은 지적인 것 같습니다.
확장성에서 문제가 되겠어요.

string value를 vector<string> values로 바꾸는 것은 어떤가요?
혹시 다른 좋은 의견 있으실까요?

**Comment by jh-cra** [comment]
vector 바꾸는 의견에 찬성 합니다.
input 과 output 을 분리 하여 진행하는 것도 필요 한 것 같습니다.

**Comment by changhyun-cra** [comment]
네 string value를 vector<string> type으로 변경하도록 하겠습니다.
추가로 Command class에서 Shell로 값을 return 하는 것이 아닌,
별도의 Printer 모듈을 만들어서 해당 모듈에서 cout을 진행하는 방향으로 개선하도록 하겠습니다.

**Comment by bootplus-hub** [comment]
> 네 string value를 vector type으로 변경하도록 하겠습니다. 추가로 Command class에서 Shell로 값을 return 하는 것이 아닌, 별도의 Printer 모듈을 만들어서 해당 모듈에서 cout을 진행하는 방향으로 개선하도록 하겠습니다.

좋은 의견 같습니다!!
한 가지 더 의견을 첨언 하자면,

저희가 Command에 대한 arguments 를 shell 에서 parsing 해서 struct로 전달 하도록 되어 있는데요.
생각해보니 이렇게 할 경우 command의 종류 마다 해당 arguments의 종류와 수량이 다를 경우
shell 에서 command type 마다 서로 다르게 검증을 해야 하는 문제가 생길 것 같아요. ㅠㅠ

이 부분도 command 단에서 vector<string> 으로 arguments를 받아서
1. 필요한 argument의 수량 확인
2. argument의 순서에 따른 type 확인

등을 검증하는 방법은 어떨까요?

```cpp
void execute(cosnt vector<string>& arguments) {
    // argument에 수량 확인 -> throw
    // argument 의 index 마다 data type 검증
    // ISSD 실행
    // 출력이 필요한 경우 cout
}
```

이렇게 되면 
```cpp
struct CommandArgs
```
가 없어도 될 것 같아요.

**Comment by bootplus-hub** [comment]
우선 제가 ICommand에
```cpp
vurtual void execute(cosnt vector<string>& arguments) = 0;
```
을 추가하는 내용에 대해서
hotfix로 branch 하나 새로 작업해서 PR 올리겠습니다.

**Comment by bootplus-hub** [comment]
feature/shell-hotfix-command

> 우선 제가 ICommand에
> 
> ```c++
> vurtual void executeArgs(cosnt vector<string>& arguments) = 0;
> ```
> 
> 을 추가하는 내용에 대해서 hotfix로 branch 하나 새로 작업해서 PR 올리겠습니다.

feature/shell 을 기반으로 feature/shell-hotfix-command branch 하나 올렸습니다.

```c++
interface ICommand {
vurtual void execute(cosnt vector<string>& args) = 0;
...
}
```

기존 execute method에 args의 type을 변경하는 것으로 하였고,
관련하여 컴파일 오류 나지 않도록 우선 임시 반영 해두었습니다.
임시 반영한 부분에 대해서는
```cpp
// TODO: hotfix 반영 부분 수정 필요
```
주석을 달아두었으며,
기존 Test Case 가 Fail이 나는 부분에 대해서 확인 하셔서 반영 해주시면 될 것 같습니다.

args 로 전달되는 내용은

command명 이후로 shell에서 입력 받은 내용에 대해서 split 하여 전달할 예정입니다.
