### ISSUE TITLE
fullwrite 오류

### ISSUE THREAD

**Issue by jh-cra** [mhkim90/ssdproject-1234#74]
이슈: 
fullwrite command 입력 후, 출력 이상 및 write 결과 오류

이슈 상세:
shell command 창에서 fullwrite 0x12345678 를 입력 하였고, 아래 현상과 같이 많은 화면 출력이 발생하고, 실행 시간이 오래 걸립니다.
read 해서 확인 해보면 올바른 write 가 안 된 것으로 보입니다.

현상:
1. fullwrite 수행
2. fullwrite 수행 완료 후 read 수행

**SHELL > fullwrite 0x12345678**
open file has to be called for once
openFile str :2 0 0xABCDABCD
****** print cmd List *******
opcode: 2, lba : 0, data: 0xABCDABCD
total command buffer pool cmd count : 1
writeFile is called :
open file has to be called for once
openFile str :2 0 0x12345678
****** print cmd List *******
opcode: 2, lba : 0, data: 0x12345678
total command buffer pool cmd count : 1
writeFile is called :
open file has to be called for once
openFile str :2 0 0x12345678
openFile str :2 1 0x12345678
****** print cmd List *******
opcode: 2, lba : 0, data: 0x12345678
opcode: 2, lba : 1, data: 0x12345678
total command buffer pool cmd count : 2
...
writeFile is called :
open file has to be called for once
openFile str :2 0 0x12345678
openFile str :2 1 0x12345678
openFile str :2 2 0x12345678
openFile str :2 3 0x12345678
openFile str :2 4 0x12345678
openFile str :2 5 0x12345678
openFile str :2 6 0x12345678
openFile str :2 7 0x12345678
openFile str :2 8 0x12345678
openFile str :2 9 0x12345678
****** print cmd List *******
opcode: 2, lba : 0, data: 0x12345678
opcode: 2, lba : 1, data: 0x12345678
opcode: 2, lba : 2, data: 0x12345678
opcode: 2, lba : 3, data: 0x12345678
opcode: 2, lba : 4, data: 0x12345678
opcode: 2, lba : 5, data: 0x12345678
opcode: 2, lba : 6, data: 0x12345678
opcode: 2, lba : 7, data: 0x12345678
opcode: 2, lba : 8, data: 0x12345678
opcode: 2, lba : 9, data: 0x12345678
total command buffer pool cmd count : 10
writeFile is called :
open file has to be called for once
openFile str :2 0 0x12345678
openFile str :2 1 0x12345678
openFile str :2 2 0x12345678
openFile str :2 3 0x12345678
openFile str :2 4 0x12345678
openFile str :2 5 0x12345678
openFile str :2 6 0x12345678
openFile str :2 7 0x12345678
openFile str :2 8 0x12345678
openFile str :2 9 0x12345678
...
open file has to be called for once
openFile str :2 0 0x12345678
openFile str :2 1 0x12345678
openFile str :2 2 0x12345678
openFile str :2 3 0x12345678
openFile str :2 4 0x12345678
openFile str :2 5 0x12345678
openFile str :2 6 0x12345678
openFile str :2 7 0x12345678
openFile str :2 8 0x12345678
openFile str :2 9 0x12345678

**SHELL > read 0**
open file has to be called for once
openFile str :2 0 0x12345678
openFile str :2 1 0x12345678
openFile str :2 2 0x12345678
openFile str :2 3 0x12345678
openFile str :2 4 0x12345678
openFile str :2 5 0x12345678
openFile str :2 6 0x12345678
openFile str :2 7 0x12345678
openFile str :2 8 0x12345678
openFile str :2 9 0x12345678
0xABCDABCD
**SHELL > read 1**
open file has to be called for once
openFile str :2 0 0x12345678
openFile str :2 1 0x12345678
openFile str :2 2 0x12345678
openFile str :2 3 0x12345678
openFile str :2 4 0x12345678
openFile str :2 5 0x12345678
openFile str :2 6 0x12345678
openFile str :2 7 0x12345678
openFile str :2 8 0x12345678
openFile str :2 9 0x12345678
0xABCDABCD

**Comment by jjuun0105v** [comment]
ssd에서 buffer clear하여 이후 10부터 다시 command 받아줄 수 있도록 수정하였습니다.
