### ISSUE TITLE
SSD Erase Issue

### ISSUE THREAD

**Issue by changhyun-cra** [mhkim90/ssdproject-1234#86]
![image](https://github.com/mhkim90/ssdproject-1234/assets/173645510/44c17379-6661-43af-8772-a8dfec097d96)

SHELL > fullwrite 0x12341234
SHELL > erase 0 10
SHELL > fullread
SHELL > erase 91 10

**Comment by jh-cra** [comment]
![image](https://github.com/mhkim90/ssdproject-1234/assets/174404628/0fce792c-7f50-433c-ade7-0031441bca39)

SHELL > fullwrite 0x99999999
SHELL > write 5 0xAAAAAAAA
SHELL > write 6 0xBBBBBBBB
SHELL > write 7 0xCCCCCCCC
SHELL > fullread
0x99999999
0x99999999
0x99999999
0x99999999
0x99999999
0xAAAAAAAA
0xBBBBBBBB
0xCCCCCCCC
0x99999999
...

<=== 아래의 command 를 수행 하니 팝업에러 발생 하였습니다.
SHELL > erase 6 3

**Comment by seulgiishin** [comment]
#94 로 수정한 코드 반영해두었습니다~ 감사합니다!!
